# Dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files to container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the app
CMD ["unicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
